# 参考配置文件
# org.springframework.cloud.config.server.environment.NativeEnvironmentRepository
# 支持占位符 {application}, {profile}, {label}

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config-files/
