server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
# 参考配置类: org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean
  instance:
    hostname: localhost
  client:
    # 参考配置类: org.springframework.cloud.netflix.eureka.EurekaClientConfigBean
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


# eureka 加密配置
# pom.xml 引入包 org.springframework.boot:spring-boot-starter-security
# 加入 security 配置:
# spring:
#   security:
#     user:
#       name: taichi
#       password: 123456
#       roles: user
# defaultZone 配置:
# defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
# 记得关闭 security 的 csrf ,否则会导致客户端服务无法注册到 eureka 中
# 生产环境可将 csrf 设置为 sameOrigin ,以避免外部服务注册进来
