version: '3'
services:
  spring-boot-sample:
    build: ../spring-boot-sample
    ports:
      - "8080:8080"
    networks:
      - spring-sample

  spring-jpa-sample:
    build: ../spring-jpa-sample
    ports:
      - "8080:8080"
    networks:
      - spring-sample

#  quartz-sample:
#    build: ../quartz-sample
#    ports:
#      - "8080:8080"
#    networks:
#      - spring-sample

#  mybatis-sample:
#    build: ../mybatis-sample
#    ports:
#      - "8080:8080"
#    networks:
#      - spring-sample

#  rabbitmq:
#    image: rabbitmq:3.8-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - "/data/rabbitmq:/var/lib/rabbitmq"
#    hostname: rabbit-spring
#    environment:
#      RABBITMQ_DEFAULT_VHOST: spring
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: admin
#    networks:
#      - spring-sample

#    mariadb:
#      image: mariadb:10.4-bionic
#      ports:
#        - "3306:3306"
#      volumes:
#        - "/data/mariadb/conf:/etc/mysql/conf.d"
#        - "/data/mariadb/data:/var/lib/mysql"
#      environment:
#        MYSQL_ROOT_PASSWORD: maria1234
#      networks:
#        - spring-sample

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes: 
      - "/data/redis/data:/data"
      - "/data/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    networks: 
      - spring-sample
      

  prometheus: 
    image: prom/prometheus:v2.19.2
    container_name: prometheus
    ports: 
      - "9090:9090"
    volumes: 
      - "/data/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml"

networks:
  spring-sample:
