server:
  port: 8099

spring:
  application:
    name: mybatis-sample

  datasource:
    url: jdbc:h2:mem:testdb2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false

