#security:
#  oauth2:
#    client:
#      client-id: first-client
#      client-secret: noonewilleverguess
      
      
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: /.well-known/jwks.json

spring:
  application:
    name: authorization-server
  
  datasource:
    url: jdbc:h2:mem:auth
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  h2: 
    console: 
      enabled: true
      path: /h2-console
      settings: 
        trace: false
        web-allow-others: false
        
  flyway:
    baseline-on-migrate: true