server:
  port: 9999

spring:
  application: 
    name: spring-flyway-sample
    
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration,classpath:db/migration/{vendor}
# {vendor} 代表供应商,可以是  mysql oracle h2 等,参考: org.springframework.boot.jdbc.DatabaseDriver

# 配置 h2数据库 可以在网页上访问
  h2: 
    console: 
      enabled: true
      path: /h2-console
      settings: 
        trace: true
        web-allow-others: false
 
# 配置数据源        
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: